### ISSUE TITLE
Any chance to work with MediaRecorder?

### ISSUE THREAD

**Issue by UdiOshi85** [akshay2211/MusicWave#1]
Hi,

I want to use the library during voice recording during MediaRecorder.
Is it possible? 

thanks

**Comment by akshay2211** [comment]
Hello @UdiOshi85 
I dont think its possible via this library 
but you can look [this link](https://stackoverflow.com/questions/14295427/android-audio-recording-with-voice-level-visualization) for visualization while recording audio

**Comment by UdiOshi85** [comment]
Thanks very much
